### ISSUE TITLE
Backspace key causes H19term.py to crash  out (tested on Pi 3B+)

### ISSUE THREAD

**Issue by riwide** [horga83/h19term#1]
Using H19Term.py on Raspberry Pi 3B+, the backspace key causes the program to crash out. See details below:
pi@pi3b:~/Downloads/h19term-master $ ./h19term.py
Traceback (most recent call last):
  File "./h19term.py", line 1854, in <module>
    curses.wrapper(term.main, term, sio)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./h19term.py", line 1791, in main
    self.process_key(c, sio, scr, scn, st)
  File "./h19term.py", line 1729, in process_key
    self.sio_write(sio, chr(c))
ValueError: chr() arg not in range(256)
pi@pi3b:~/Downloads/h19term-master $

**Comment by riwide** [comment]
Dump seemed crossed out, try again:
~/Downloads/h19term-master $ ./h19term.py
Traceback (most recent call last):
  File "./h19term.py", line 1854, in <module>
    curses.wrapper(term.main, term, sio)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./h19term.py", line 1791, in main
    self.process_key(c, sio, scr, scn, st)
  File "./h19term.py", line 1729, in process_key
    self.sio_write(sio, chr(c))
ValueError: chr() arg not in range(256)
~/Downloads/h19term-master $

**Comment by riwide** [comment]
verified that problem also occurs on macos osx 10.12.4 with python2.
fyi: pylint comes up with a lot of messages when run against h10term.rc - I had hoped it would be cleaner and any messages from pylint might relate to the problem described.

**Comment by horga83** [comment]
Had a quick look at this.

One must set your terminal emulator to have CTRL-H for a backspace? 
Looks like I may have missed this in the docs, also I will do a test
for this when running.  Gnome Terminal and XFCE-terminal can be set
from the preferences, I expect most others as well.  I set this in a
profile and run h19term with that.

George

**Comment by riwide** [comment]
I comprehend that one should configure H19Term for correct behaviour
against the backend, but I would not expect the terminal to crash if
unexpected data is received, especially as sometimes one chooses a terminal
emulation as best but not exact match to host end. Have you written H19term
with sufficient defensive programming?

I was using h19term as configured by default to a CP/M backend running a
number of software packages configured for H19/Z19.

Regards

Richard

**Comment by horga83** [comment]
Defensive programming?  No, no, no, no there will be none of that here,
I prefer instead to use offensive programming, something that will
really annoy the user!  Just look how well it's worked so far:-)
No worries Richard, it'll get fixed.
George

**Comment by riwide** [comment]
Cheers, love the humour!
By the way, defensive programming is often frowned upon, both parts of a
design should work together without need for it, but of course in this
instance we are constrained by the existing application designs, user
choices and lost documentation.
Richard
