### ISSUE TITLE
Esc r crashes h19term

### ISSUE THREAD

**Issue by hackerb9** [horga83/h19term#9]
```log
$ echo -e '\er'
Traceback (most recent call last):
  File "/home/ben/src/h19term/./h19term.py", line 2558, in <module>
    curses.wrapper(term.main, term, sio)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/ben/src/h19term/./h19term.py", line 2537, in main
    term.process_escape_seq(sio)
  File "/home/ben/src/h19term/./h19term.py", line 962, in process_escape_seq
    self.heath_escape_seq(sio)
  File "/home/ben/src/h19term/./h19term.py", line 1024, in heath_escape_seq
    self.modify_baudrate(sio, self.baudrate[rate - 65]) #'A' - 65 = 0
IndexError: list index out of range
```

**Comment by horga83** [comment]
ok I'll look into it.
